# Generated by Django 2.1.1 on 2018-10-18 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('YAAS_App', '0003_auto_20181018_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlanguage',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
