# Generated by Django 2.1.1 on 2018-10-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auctions', '0002_auto_20181013_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='current_bid',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='status',
            field=models.IntegerField(choices=[(1, 'Banned'), (2, 'Active'), (3, 'Due')], default=2),
        ),
    ]
