# Generated by Django 2.1.1 on 2018-10-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auctions', '0006_auto_20181015_2023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auction',
            options={'ordering': ['deadline']},
        ),
        migrations.AddField(
            model_name='auction',
            name='language_pref',
            field=models.IntegerField(choices=[(1, 'English'), (2, 'Swedish')], default=1),
        ),
    ]
