# Generated by Django 2.1.1 on 2018-10-18 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auctions', '0007_auto_20181018_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='language_pref',
        ),
    ]
