# Generated by Django 2.1.1 on 2018-10-19 10:54

import concurrency.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auctions', '0008_remove_auction_language_pref'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='version',
            field=concurrency.fields.ConditionalVersionField(default=0, help_text='record revision number'),
        ),
        migrations.AddField(
            model_name='auction',
            name='winning_bid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winning_bid', to='Auctions.Bid'),
        ),
    ]
