# Generated by Django 2.1.1 on 2018-10-24 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auctions', '0009_auto_20181019_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='winning_bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winning_bid', to='Auctions.Bid'),
        ),
    ]
